# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu : [10,50,100,500]
        pageLength: 10
        searching: true
        dom: '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-4 col-md-4"l><"col-sm-4 dt-action-buttons text-center"B><"col-sm-4 col-md-4"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>'
#        dom: "<'row' <'col-sm-12 col-md-6' l> <'col-sm-12 col-md-6' f>> <'row' <'col-sm-12' tr>> <'row' <'col-sm-12 col-md-5' i> <'col-sm-12 col-md-7' p> > "
        fixedHeader: true
    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
#        className: 'table table-striped table-bordered table-hover data-table'
        className: 'table table-bordered'
        #className: 'table table-bordered table-sm table-striped dataex-html5-selectors dataTable dt-multilingual table no-footer dtr-column table-hover'
    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'
