index:
    path: /
    controller: App\Controller\ResultController::index

result_ajax:
    path: /result_ajax
    controller: App\Controller\ResultController::resultAjax
    
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /admin
    name_prefix: app.admin