index:
    path: /
    controller: App\Controller\SecurityController::login
    
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation
    prefix: /admin
    name_prefix: app.admin